# Generated by Django 3.1.1 on 2021-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tbl_login_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_login',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='information/pdfs/'),
        ),
        migrations.AlterField(
            model_name='tbl_login',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='information/images/'),
        ),
    ]
