# Generated by Django 3.1.1 on 2021-06-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210616_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_login',
            old_name='picture',
            new_name='pictures',
        ),
    ]
